source 'https://rubygems.org'

#Core Management
gem 'rails', '4.1.6'
gem 'pg' #THIS SHOULD NOT BE IN YOUR IN GEM FILE 

#Front End Management
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'
gem 'simple_form'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'spring',        group: :development

gem 'annotate'

#Testing & Debugging Tools 
group :development do
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'pry'
  gem 'pry-byebug'
  gem 'thin'
end

#Documentation Stuff
gem 'sdoc', '~> 0.4.0',          group: :doc

